version: '3.8' 

services:  
  db:
    container_name: solarcoffe_db
    hostname: solarcoffe_db
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - dbcredentials.env
    volumes:
      - dbvol:/var/lib/postgresql/data/

volumes:
  dbvol: